version: '3.8'

services:
  admin:
    build:
      context: ./admin
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=${POSTGRESQL_DATABASE}
      - DATABASE_USER=${POSTGRESQL_ROOT_USER}
      - DATABASE_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - DATABASE_HOST=db
      - DATABASE_PORT=${POSTGRESQL_PORT}

  qna_engine:
    build:
      context: ./qna_engine
    ports:
      - 7000:7000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongo://mongo:27017/qna_engine

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRESQL_ROOT_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PORT}:5432"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      -"${MONGO_PORT}:27017"
    volumes:
      -./data/mongo:data/db

volumes:
  pg_data:
