version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    port:
      - 2181:2181

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    volumes:
      - ./data/kafka:/var/run/docker.sock
    environment:
      - KAFKA_ADVERTISED_HOST_NAME:kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  admin:
    build:
      context: ./admin
    ports:
      - 8000:8000
    depends_on:
      - postgres
    environment:
      - DATABASE_NAME=${POSTGRESQL_DATABASE}
      - DATABASE_USER=${POSTGRESQL_ROOT_USER}
      - DATABASE_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${POSTGRESQL_PORT}

  qna_engine:
    build:
      context: ./qna_engine
    ports:
      - 4000:4000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/qna_engine

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRESQL_ROOT_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRESQL_PORT}:5432"

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data/mongo:/data/db

volumes:
  pg_data:
